datasource:
  secondary:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url:  jdbc:mysql://192.168.5.30:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT
    username: test
    password: test