server:
  port: 8686 #服务端口号
spring:
  application:
    name: DemoSystem #服务名称--调用的时候根据名称来调用该服务的方法
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
        generate_statistics: true
    open-in-view: false